#!/usr/bin/env python3
"""Smoke test for per-game ESPN final grading in sports_system_runner.py.

Creates an isolated temporary sports_picks tree, builds a tiny workbook for a
recently completed ESPN game, grades that one game, and prints the graded rows.
It does not touch production workbooks, bankroll files, Obsidian notes, or
Telegram.
"""
from __future__ import annotations

import importlib.util
import json
import shutil
import tempfile
from datetime import datetime, timedelta
from pathlib import Path

RUNNER_PATH = Path('/Users/akashkalita/sports_picks/scripts/sports_system_runner.py')
spec = importlib.util.spec_from_file_location('sports_system_runner', RUNNER_PATH)
runner = importlib.util.module_from_spec(spec)
spec.loader.exec_module(runner)


def patch_isolated_paths(root: Path) -> None:
    runner.ROOT = root
    runner.DATA = root / 'data'
    runner.NBA_DIR = runner.DATA / 'nba'
    runner.MLB_DIR = runner.DATA / 'mlb'
    runner.PNL_DIR = runner.DATA / 'pnl'
    runner.LOG_DIR = runner.PNL_DIR / 'logs'
    runner.SCRIPTS = root / 'scripts'
    runner.RUN_LOG = runner.LOG_DIR / 'run_log.txt'
    runner.BANKROLL = runner.PNL_DIR / 'bankroll.json'
    runner.LOCK_FILE = runner.LOG_DIR / 'sports_system_runner.lock'
    runner.GAME_STATUS_CACHE_FILE = runner.PNL_DIR / 'game_status_cache.json'
    runner.OBSIDIAN_BASE = root / 'obsidian' / 'SportsEdge'
    runner.OBSIDIAN_DASHBOARD = runner.OBSIDIAN_BASE / 'Dashboard'
    runner.OBSIDIAN_PICKS = runner.OBSIDIAN_BASE / 'Picks'
    runner.OBSIDIAN_RESEARCH_PLAYERS = runner.OBSIDIAN_BASE / 'Research' / 'Players'
    runner.OBSIDIAN_RECAPS_WEEKLY = runner.OBSIDIAN_BASE / 'Recaps' / 'Weekly'
    runner.OBSIDIAN_INTEL = runner.OBSIDIAN_BASE / 'Intel'
    runner.OBSIDIAN_META = runner.OBSIDIAN_BASE / 'Meta'
    runner.send_telegram = lambda message: {'status': 'skipped_in_smoke_test', 'message': message}


def find_recent_final_game() -> tuple[str, str, dict]:
    today = datetime.now()
    for days_back in range(0, 14):
        date = (today - timedelta(days=days_back)).strftime('%Y-%m-%d')
        for sport in ('mlb', 'nba'):
            games = runner.espn_scoreboard_games_for_date(sport, date)
            finals = [g for g in games if g.get('status') == 'final' and g.get('home_score') is not None and g.get('away_score') is not None]
            if finals:
                return sport, date, finals[0]
    raise SystemExit('No recent completed NBA/MLB ESPN game found for smoke test')


def build_test_workbook(sport: str, date: str, game: dict) -> Path:
    runner.ensure_dirs()
    path = runner.ensure_workbook(sport, date)
    wb = runner.load_workbook(path)
    picks = wb['Picks']
    props = wb['Props']
    away = game['away_team']
    home = game['home_team']
    away_score = int(game['away_score'])
    home_score = int(game['home_score'])
    winner = home if home_score > away_score else away
    total = home_score + away_score
    event_id = game['event_id']
    # Guaranteed WINs based on the known final: winner -0.5, over final_total-0.5.
    picks.append([date, sport.upper(), event_id, '', away, home, 'SPREAD', winner, -0.5, -110, 'A', 1.0, 'ACTIVE', 'Smoke test spread pick'])
    picks.append([date, sport.upper(), event_id, '', away, home, 'TOTAL', 'Over', total - 0.5, -110, 'B', 1.0, 'ACTIVE', 'Smoke test total pick'])
    # Add one prop when ESPN box score exposes a usable stat.
    stats = runner.espn_player_stats_by_event(sport, event_id)
    for name, row in stats.items():
        stat_name = 'points' if sport == 'nba' else 'hits'
        actual = runner.to_float(row.get(stat_name))
        if actual is not None and actual > 0:
            display = name.title()
            props.append([date, sport.upper(), f'smoke-{event_id}-{display}', display, home, f'{display} Over {stat_name} {actual - 0.5}', stat_name, actual - 0.5, 'standard', '', 'ACTIVE', 'Generated by sports_system_runner smoke test; units=1'])
            break
    runner.save_workbook_atomic(wb, path)
    return path


def main() -> int:
    temp_root = Path(tempfile.mkdtemp(prefix='sports_game_monitor_smoke_'))
    try:
        patch_isolated_paths(temp_root)
        sport, date, game = find_recent_final_game()
        workbook = build_test_workbook(sport, date, game)
        result = runner.grade_game_in_workbook(sport, game, date=date, dry_run=False)
        output = {
            'smoke_root': str(temp_root),
            'sport': sport.upper(),
            'date': date,
            'event_id': game.get('event_id'),
            'game': result.get('game'),
            'final_score': f"{game.get('away_team')} {game.get('away_score')} @ {game.get('home_team')} {game.get('home_score')}",
            'workbook': str(workbook),
            'graded_count': len(result.get('graded', [])),
            'graded': result.get('graded', []),
            'bankroll': result.get('bankroll'),
            'day_pnl': result.get('day_pnl'),
            'current': result.get('current'),
            'recap': runner.build_game_recap(result),
        }
        print(json.dumps(output, indent=2, default=str))
        return 0 if output['graded_count'] >= 2 else 1
    finally:
        # Keep tmp tree for inspection only when requested by env in future; default cleanup.
        shutil.rmtree(temp_root, ignore_errors=True)


if __name__ == '__main__':
    raise SystemExit(main())
